// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqsoaointtaqagmtqdao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxxc29hb2ludHRhcWFnbXRxZGFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODkyMzcsImV4cCI6MjA1OTY2NTIzN30.WlNVaoDdOxG-8up-uaETKppZzqH3fReM1_HD7WcQbU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);